### ISSUE TITLE
Test backup and restore

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4263]
Make a backup of this account http://moblix.admin.kademi-ci.co/

And restore it into a new account.  You will also need to copy across content using the admin URL.

Things to check, but is not limited to:

- [x] - All websites + webpages are copied across (note this failed when I did it) ( https://github.com/Kademi/kademi-dev/issues/4285 & https://github.com/Kademi/kademi-dev/issues/4286 )
- [x] - Journeys
- [x] - Data series + KPIs and their configurations (note not all config copied for me)
- [x] - Blogs and their correct tags and cats (note tags and cats were lost for me)
- [x] - Levels and badges ( https://github.com/Kademi/kademi-dev/issues/4307 )
- [x] - Surveys including k-feedback and k-survey
- [x] - Group emails
- [x] - Users profiles
- [x] - Note APPs were switched on but did appear in the admin menu.  Brad said something about the files needed touching to fix this.
- [x] - Reward stores
- [x] - Auctions ( https://github.com/Kademi/kademi-dev/issues/4323 )
- [x] - Dashboard alerts - Depends on https://github.com/Kademi/kademi-dev/issues/4274
- [x] - All learning programs, courses and modules for each website
- [x] - Groups
- [x] - Organisations
- [x] - Polls

Please run the backup and restore copying Moblix into a new account and identify the gaps.

**Comment by paddyow** [comment]
@tuzzmaniandevil can you copy

http://moblix.admin.kademi-ci.co/

Into...

http://synchro.admin.kademi.com.au/

**Comment by Uafinder** [comment]
Backup duration - 4 mins 30 secs...

**Comment by bradmac** [comment]
> Statistics data empty

This is correct. You will need to manually reindex after restoring

**Comment by bradmac** [comment]
Moved non-urgent issues here - https://github.com/Kademi/kademi-dev/issues/4356

**Comment by tuzzmaniandevil** [comment]
1. Fixed
2. Fixed
3. The Dyna group doesn't work in Moblix either, It doesn't have any queries.

**Comment by Uafinder** [comment]
Restore does nothing:
from
http://moblix.admin.kademi-ci.co/
to
http://moblixvideos.admin.kademi.com.au/backup/

try this one
![image](https://user-images.githubusercontent.com/1945230/33172275-24bd70c8-d058-11e7-9a74-6d103697a517.png)
and simple kademi-ci.co for admin URL

As a result, restore is not happening.

**Comment by tuzzmaniandevil** [comment]
There is an issue that stop the status from showing, But the restore does actually progress and work.
![upload_restore](https://user-images.githubusercontent.com/3378330/33190147-6e50274c-d10e-11e7-920d-767aba72847d.png)

Here is the result:
![image](https://user-images.githubusercontent.com/3378330/33190382-08e1f5e0-d111-11e7-9636-d753ce377105.png)

**Comment by tuzzmaniandevil** [comment]
http://moblixvideos.admin.kademi.com.au/backup/

**Comment by Uafinder** [comment]
1. Deleted groups appears
![image](https://user-images.githubusercontent.com/1945230/33215000-c847d3ee-d136-11e7-9583-c4399e7f7485.png)
![image](https://user-images.githubusercontent.com/1945230/33215014-d23a9ecc-d136-11e7-9626-f2fd2b1ea810.png)

2. No disabled users are copied
![image](https://user-images.githubusercontent.com/1945230/33215065-0bc2230e-d137-11e7-8981-cd72188a4ae9.png)
![image](https://user-images.githubusercontent.com/1945230/33215054-fca75af6-d136-11e7-9916-e3877881038b.png)

3. Orgs are not copied
![image](https://user-images.githubusercontent.com/1945230/33215093-2fe16c86-d137-11e7-910e-5063942a84f3.png)
![image](https://user-images.githubusercontent.com/1945230/33215108-3b2788d2-d137-11e7-9d58-c5a3d7955512.png)

4. Leads are not copied
http://moblix.admin.kademi-ci.co/funnels/sales-claims/version1/leads/
http://moblixvideos.admin.kademi.com.au/funnels/sales-claims/version1/leads/

5. posts are not copied
![image](https://user-images.githubusercontent.com/1945230/33215238-bc01210c-d137-11e7-8dd2-aa83ea310f5b.png)
![image](https://user-images.githubusercontent.com/1945230/33215246-c143fc66-d137-11e7-9deb-0e8cd21306c6.png)

6. Reward points are not copied
![image](https://user-images.githubusercontent.com/1945230/33215301-e82c314a-d137-11e7-9fd2-cebdcb054d95.png)
![image](https://user-images.githubusercontent.com/1945230/33215310-eeb0238c-d137-11e7-86b4-c1f27aa72f6d.png)

7. Reward stores are not copied
![image](https://user-images.githubusercontent.com/1945230/33215352-16917194-d138-11e7-9095-645d2d3bc093.png)
![image](https://user-images.githubusercontent.com/1945230/33215360-1bb6c6c4-d138-11e7-8dd1-a1cc61a32323.png)

8. Orders not copied
![image](https://user-images.githubusercontent.com/1945230/33215401-45ea9286-d138-11e7-8847-3ae0a48838e8.png)
![image](https://user-images.githubusercontent.com/1945230/33215405-4b0858a2-d138-11e7-807b-a50c9b9b2619.png)

9. points allocation rules empty
![image](https://user-images.githubusercontent.com/1945230/33215425-5f86a19e-d138-11e7-8fd0-294d2182a12e.png)
![image](https://user-images.githubusercontent.com/1945230/33215435-63ded8f6-d138-11e7-8d41-91688559abfd.png)

10. KPI data is not copied
![image](https://user-images.githubusercontent.com/1945230/33215514-d2557cb8-d138-11e7-8d33-3c7afc3fe147.png)
![image](https://user-images.githubusercontent.com/1945230/33215519-d6ebf82e-d138-11e7-9a8f-76c7e6d44a94.png)

11. Points tags are not copied

http://moblix.admin.kademi-ci.co/
http://moblixvideos.admin.kademi.com.au/reporting/

**Comment by bradmac** [comment]
> No disabled users are copied

This is correct. Disabled users are considered deleted, and deleted data should generally not be restored
